class ActivityAction:
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"

    PDF_UPLOAD = "PDF_UPLOAD"
    DOCUMENT_SEARCH = "DOCUMENT_SEARCH"
    DOCUMENT_EXPORT = "DOCUMENT_EXPORT"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"

    PAYMENT_INITIALIZED = "PAYMENT_INITIALIZED"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"

    USER_CREATED = "USER_CREATED"
    PASSWORD_RESET = "PASSWORD_RESET"

    ADMIN_LOGIN = "ADMIN_LOGIN"
    ADMIN_DELETE_DOCUMENT = "ADMIN_DELETE_DOCUMENT"