from enum import StrEnum

class ActivityAction(StrEnum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"

    DATASET_CREATED = "DATASET_CREATED"
    DATASET_UPDATED = "DATASET_UPDATED"

    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    SEARCH_EXECUTED = "SEARCH_EXECUTED"
    EXPORT_CREATED = "EXPORT_CREATED"
    CHAT_MESSAGE = "CHAT_MESSAGE"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED"